import { assetUrls } from "./assets";
import type { CaptainSkillSpec, CrewSpec, Faction, Good, Port, ShipSpec, UpgradeSpec } from "./types";

export const factions: Faction[] = [
  {
    id: "charter",
    name: "Charter Bank",
    policy: "credit and tariffs",
    tariffGoods: ["silk", "medicine"],
    color: "#367c9a",
  },
  {
    id: "freeports",
    name: "Freeport Compact",
    policy: "speed and open docks",
    tariffGoods: ["iron", "tools"],
    color: "#4fa36c",
  },
  {
    id: "admiralty",
    name: "Admiralty Court",
    policy: "convoys and patrol law",
    tariffGoods: ["spice", "silk"],
    color: "#c8503e",
  },
  {
    id: "league",
    name: "Dockworkers League",
    policy: "labor leverage",
    tariffGoods: ["glass", "medicine"],
    color: "#d6a43a",
  },
];

export const ports: Port[] = [
  {
    id: "grayhaven",
    name: "Grayhaven",
    x: 0.18,
    y: 0.63,
    risk: 0.16,
    flavor: "A foggy exchange where clerks price risk with ink-stained fingers.",
    faction: "charter",
    exports: ["iron", "tools"],
    imports: ["silk", "medicine"],
    asset: assetUrls.ports.grayhaven,
  },
  {
    id: "saffron",
    name: "Saffron Quay",
    x: 0.34,
    y: 0.28,
    risk: 0.23,
    flavor: "A spice harbor with fast talkers, faster ships, and very real shortages.",
    faction: "freeports",
    exports: ["spice", "tea"],
    imports: ["iron", "tools"],
    asset: assetUrls.ports.saffron,
  },
  {
    id: "glassport",
    name: "Glassport",
    x: 0.57,
    y: 0.48,
    risk: 0.2,
    flavor: "Tall warehouses, careful bankers, and contracts written in tiny print.",
    faction: "charter",
    exports: ["glass", "medicine"],
    imports: ["tea", "spice"],
    asset: assetUrls.ports.glassport,
  },
  {
    id: "stormhook",
    name: "Stormhook",
    x: 0.78,
    y: 0.22,
    risk: 0.34,
    flavor: "A hard northern port where sailors buy cannons before coats.",
    faction: "admiralty",
    exports: ["iron", "medicine"],
    imports: ["silk", "tea"],
    asset: assetUrls.ports.stormhook,
  },
  {
    id: "orchid",
    name: "Orchid Roads",
    x: 0.82,
    y: 0.68,
    risk: 0.27,
    flavor: "Quiet docks, deep pockets, and silk buyers who never blink first.",
    faction: "freeports",
    exports: ["silk", "glass"],
    imports: ["tools", "spice"],
    asset: assetUrls.ports.orchid,
  },
  {
    id: "lowmarket",
    name: "Lowmarket",
    x: 0.47,
    y: 0.76,
    risk: 0.18,
    flavor: "A practical harbor where every crate gets weighed twice.",
    faction: "league",
    exports: ["tools", "tea"],
    imports: ["medicine", "glass"],
    asset: assetUrls.ports.lowmarket,
  },
];

export const goods: Good[] = [
  { id: "tea", name: "Tea", base: 42, cargo: 1, note: "steady", volatility: 0.032 },
  { id: "spice", name: "Spice", base: 68, cargo: 1, note: "volatile", volatility: 0.065 },
  { id: "silk", name: "Silk", base: 96, cargo: 1, note: "luxury", volatility: 0.052 },
  { id: "iron", name: "Iron", base: 50, cargo: 2, note: "heavy", volatility: 0.038 },
  { id: "tools", name: "Tools", base: 74, cargo: 2, note: "industrial", volatility: 0.042 },
  { id: "medicine", name: "Medicine", base: 88, cargo: 1, note: "scarce", volatility: 0.058 },
  { id: "glass", name: "Glass", base: 58, cargo: 1, note: "fragile", volatility: 0.046 },
];

export const shipCatalog: ShipSpec[] = [
  {
    id: "coastal_sloop",
    name: "Coastal Sloop",
    asset: assetUrls.ships.coastal_sloop,
    role: "starter",
    silhouette: "low single-mast cutter",
    upgradePath: "rigging and weather glass",
    handling: {
      windAffinity: 0.026,
      currentAffinity: 0.008,
      roughWaterRelief: 0,
      cargoDragModifier: 1.08,
      cargoRiskModifier: 1.06,
      riskModifier: 0.004,
      wearModifier: 1.03,
      resaleModifier: 0.94,
    },
    price: 0,
    cargoCap: 20,
    cannons: 1,
    speed: 1,
    openWater: 1,
    crewCap: 2,
    hullMax: 100,
    note: "cheap, nimble, unforgiving in heavy water",
  },
  {
    id: "ledger_brig",
    name: "Ledger Brig",
    asset: assetUrls.ships.ledger_brig,
    factionId: "charter",
    role: "balanced",
    silhouette: "square two-mast trader",
    upgradePath: "weather glass, cargo hoist, crew quarters",
    handling: {
      windAffinity: 0.018,
      currentAffinity: 0.012,
      roughWaterRelief: 0.014,
      cargoDragModifier: 0.96,
      cargoRiskModifier: 0.96,
      riskModifier: -0.006,
      wearModifier: 0.96,
      resaleModifier: 1.05,
    },
    price: 2400,
    cargoCap: 32,
    cannons: 2,
    speed: 2,
    openWater: 2,
    crewCap: 3,
    hullMax: 110,
    note: "balanced trader with room to specialize",
  },
  {
    id: "clipper_kite",
    name: "Clipper Kite",
    asset: assetUrls.ships.clipper_kite,
    factionId: "freeports",
    role: "clipper",
    silhouette: "long narrow wind knife",
    upgradePath: "deep rigging, smuggler locker, navigator",
    handling: {
      windAffinity: 0.078,
      currentAffinity: 0.026,
      roughWaterRelief: 0.018,
      cargoDragModifier: 1.08,
      cargoRiskModifier: 1.04,
      riskModifier: 0.008,
      wearModifier: 1.02,
      resaleModifier: 1.02,
    },
    price: 4200,
    cargoCap: 28,
    cannons: 1,
    speed: 4,
    openWater: 3,
    crewCap: 3,
    hullMax: 96,
    note: "route hunter that turns tailwinds into money",
  },
  {
    id: "harbor_cutter",
    name: "Harbor Cutter",
    asset: assetUrls.ships.harbor_cutter,
    factionId: "admiralty",
    role: "patrol",
    silhouette: "compact two-sail customs cutter",
    upgradePath: "customs ledger, signal cannon, long nines, watch bunks",
    handling: {
      windAffinity: 0.042,
      currentAffinity: 0.018,
      roughWaterRelief: 0.034,
      cargoDragModifier: 1.02,
      cargoRiskModifier: 0.93,
      riskModifier: -0.026,
      wearModifier: 0.92,
      resaleModifier: 1.04,
    },
    price: 3600,
    cargoCap: 24,
    cannons: 3,
    speed: 3,
    openWater: 3,
    crewCap: 3,
    hullMax: 104,
    note: "small hold, sharp papers, and enough guns to make risky lanes negotiable",
  },
  {
    id: "iron_barge",
    name: "Iron Barge",
    asset: assetUrls.ships.iron_barge,
    factionId: "admiralty",
    role: "barge",
    silhouette: "broad armored cargo slab",
    upgradePath: "gun deck, reinforced ribs, crew quarters",
    handling: {
      windAffinity: -0.016,
      currentAffinity: -0.012,
      roughWaterRelief: 0.062,
      cargoDragModifier: 0.8,
      cargoRiskModifier: 0.78,
      riskModifier: -0.034,
      wearModifier: 0.82,
      resaleModifier: 1.12,
    },
    price: 5200,
    cargoCap: 48,
    cannons: 3,
    speed: 1,
    openWater: 2,
    crewCap: 4,
    hullMax: 125,
    note: "slow, broad, and hard to bully",
  },
  {
    id: "league_carrier",
    name: "League Carrier",
    asset: assetUrls.ships.league_carrier,
    factionId: "league",
    role: "freighter",
    silhouette: "wide triple-hatch cargo carrier",
    upgradePath: "cargo hoist, galley mess, ballast keel",
    handling: {
      windAffinity: -0.03,
      currentAffinity: 0.004,
      roughWaterRelief: 0.026,
      cargoDragModifier: 0.62,
      cargoRiskModifier: 0.68,
      riskModifier: -0.012,
      wearModifier: 0.94,
      resaleModifier: 1.06,
    },
    price: 4600,
    cargoCap: 62,
    cannons: 1,
    speed: 1,
    openWater: 1,
    crewCap: 4,
    hullMax: 112,
    note: "huge holds, slow turns, earns money by staying loaded",
  },
];

export const equipmentCatalog: UpgradeSpec[] = [
  {
    id: "deep_rigging",
    name: "Deep-Water Rigging",
    factionId: "freeports",
    cost: 980,
    slot: "deck",
    effects: { speed: 1, openWater: 1 },
    note: "better angles in rough water",
  },
  {
    id: "cargo_hoist",
    name: "Cargo Hoist",
    factionId: "league",
    cost: 820,
    slot: "deck",
    effects: { cargoCap: 8 },
    note: "more freight without killing dock speed",
  },
  {
    id: "storm_sails",
    name: "Storm Sails",
    factionId: "freeports",
    cost: 1260,
    slot: "deck",
    effects: { speed: 2 },
    note: "fast canvas for captains who trust their water reads",
  },
  {
    id: "drogue_anchor",
    name: "Drogue Sea Anchor",
    factionId: "admiralty",
    cost: 1120,
    slot: "deck",
    effects: { openWater: 2, hullMax: 4 },
    note: "steadies beam seas and cargo slam when speed is less important than control",
  },
  {
    id: "weather_glass",
    name: "Weather Glass",
    factionId: "charter",
    cost: 760,
    slot: "instrument",
    effects: { navigation: 1, openWater: 1 },
    note: "reads trend changes before they punish you",
  },
  {
    id: "chart_table",
    name: "Chart Table",
    factionId: "charter",
    cost: 1080,
    slot: "instrument",
    effects: { navigation: 2 },
    note: "turns forecast windows into shorter crossings",
  },
  {
    id: "customs_ledger",
    name: "Customs Ledger",
    factionId: "charter",
    cost: 1240,
    slot: "instrument",
    effects: { negotiation: 2, navigation: 1 },
    note: "permit math, tariff favors, and market tells for captains who trade politics",
  },
  {
    id: "reinforced_ribs",
    name: "Reinforced Ribs",
    factionId: "admiralty",
    cost: 1120,
    slot: "hardpoint",
    effects: { hullMax: 15 },
    note: "survives bad crossings",
  },
  {
    id: "gun_deck",
    name: "Gun Deck",
    factionId: "admiralty",
    cost: 1340,
    slot: "hardpoint",
    effects: { cannons: 2 },
    note: "turns pirates into a business model",
  },
  {
    id: "long_nines",
    name: "Long Nines",
    factionId: "admiralty",
    cost: 1680,
    slot: "hardpoint",
    effects: { cannons: 3 },
    note: "heavy chase guns for captains who want encounters to notice the math",
  },
  {
    id: "ballast_keel",
    name: "Ballast Keel",
    factionId: "admiralty",
    cost: 1180,
    slot: "hardpoint",
    effects: { openWater: 2, hullMax: 8 },
    note: "steadier in ugly water, especially with freight aboard",
  },
  {
    id: "signal_cannon",
    name: "Signal Cannon",
    factionId: "charter",
    cost: 880,
    slot: "hardpoint",
    effects: { cannons: 1, navigation: 1 },
    note: "warning shot, convoy flag, and cleaner route discipline",
  },
  {
    id: "smuggler_locker",
    name: "Smuggler Locker",
    factionId: "freeports",
    cost: 900,
    slot: "instrument",
    effects: { negotiation: 1, cargoCap: 3 },
    note: "softens tariffs and inspections",
  },
  {
    id: "crew_quarters",
    name: "Crew Quarters",
    factionId: "league",
    cost: 1180,
    slot: "quarters",
    effects: { crewCap: 1, hullMax: 5 },
    note: "room for another specialist without making the ship flimsy",
  },
  {
    id: "watch_bunks",
    name: "Watch Bunks",
    factionId: "league",
    cost: 1400,
    slot: "quarters",
    effects: { crewCap: 2, openWater: 1 },
    note: "rotating watches keep extra hands useful on long rough crossings",
  },
  {
    id: "officer_cabins",
    name: "Officer Cabins",
    factionId: "charter",
    cost: 1320,
    slot: "quarters",
    effects: { crewCap: 1, navigation: 1 },
    note: "keeps senior crew rested enough to make better calls",
  },
  {
    id: "galley_mess",
    name: "Galley Mess",
    factionId: "league",
    cost: 980,
    slot: "quarters",
    effects: { crewCap: 1, negotiation: 1 },
    note: "a happier crew bargains better and lasts longer",
  },
];

export const crewCatalog: CrewSpec[] = [
  {
    id: "navigator",
    name: "Navigator",
    cost: 920,
    wage: 54,
    effects: { navigation: 2, speed: 1 },
    note: "shorter routes, fewer bad guesses",
  },
  {
    id: "quartermaster",
    name: "Quartermaster",
    cost: 860,
    wage: 48,
    effects: { negotiation: 2, cargoCap: 4 },
    note: "better prices and cleaner loading",
  },
  {
    id: "boatswain",
    name: "Boatswain",
    cost: 780,
    wage: 44,
    effects: { openWater: 1, hullMax: 8 },
    note: "keeps the ship together",
  },
  {
    id: "gunner",
    name: "Gunner",
    cost: 1100,
    wage: 58,
    effects: { cannons: 1 },
    note: "makes encounters less humiliating",
  },
];

export const captainSkillCatalog: CaptainSkillSpec[] = [
  {
    id: "navigation",
    name: "Navigation",
    effects: { navigation: 1 },
    note: "shorter routes and better wind reads",
  },
  {
    id: "seamanship",
    name: "Seamanship",
    effects: { openWater: 1 },
    note: "steadier crossings in rough water",
  },
  {
    id: "brokerage",
    name: "Brokerage",
    effects: { negotiation: 1 },
    note: "better prices, permits, and bribes",
  },
  {
    id: "gunnery",
    name: "Gunnery",
    effects: { cannons: 1 },
    note: "turns tense encounters in your favor",
  },
];
